### PR TITLE
Make test request using currently active protocol

### LINKED ISSUE #387: has.ts causes loading the main bundle to crash in Internet Explorer 11 in https
**Bug**

When using a bundled application with Internet Explorer 11 together with `https` the bundle is not loaded. IE raises an "access denied" error in the main bundle. 

Package Version: dojo RC1 (and RC2)

**Code**

can be tested with:
* create a fresh app with dojo/cli
* add the following code after the imports:

`
import request from '@dojo/core/request';
console.log(request);
`

* pack the application with `dojo build -m dist`
* access the application via https://localhost:... in IE 11

**Actual behavior:**

IE 11 will not show the rotating elements - it will show an error in the console (no SVG, ... )

### PR DESCRIPTION
**Pull request by jason0x43**
For the blob test, make the test request using the active protocol rather than always using http. At least IE11 will throw an exception when making an http request from an https domain.

**Type:** bug

The following has been addressed in the PR:

* [x] There is a related issue
* [x] All code has been formatted with [`prettier`](https://prettier.io/) as per the [readme code style guidelines](./../#code-style)
* [x] Unit or Functional tests are included in the PR (N/A)

**Description:**

Resolves #387

### CODE REVIEW

File: src/has.ts [hunk 1]
```diff
@@ -19,7 +19,7 @@ add(
 		}
 
 		const request = new global.XMLHttpRequest();
-		request.open('GET', 'http://www.google.com', true);
+		request.open('GET', global.location.protocol + '//www.google.com', true);
```
Comment (dasa) [inline src/has.ts:22]: I think it'd be better to hard-code `https` since `location.protocol` is `blob:` in a Worker created from a Blob.

Comment (szwoelf) [reply src/has.ts:22]: I did my tests also with "https" - to be exact with "https://www.google.com". I'd suggest to use it exactly like in Dojo1 (and possibly add the comment that is also there.)
```
+               // From dojo1: https://github.com/dojo/dojo/blob/master/request/xhr.js#L37
+               // The URL used here does not have to be reachable as the XHR's `send` method is never called.
+               // It does need to be parsable/resolvable in all cases, so it should be an absolute URL
+               // and it must be an https based URL for Internet Explorer 11 (when https is used).
+               // XMLHttpRequest within a Worker created from a Blob does not support relative URL paths.
+               request.open('GET', 'https://dojotoolkit.org', true);

```

Comment (jason0x43) [reply src/has.ts:22]: > I think it'd be better to hard-code https since location.protocol is blob: in a Worker created from a Blob.

Not that I'm really opposed, but why? As the comment in the dojo 1 code points out, it needs to be a parseable URL, and for IE it also must be compatible with the current location (which means https when coming from https in IE11). `global.location.protocol` works because you're just using the current protocol. Https also works, it just seems kind of arbitrary.

Comment (dasa) [reply src/has.ts:22]: I'm assuming that `blob://www.google.com` would give an error.

Comment (jason0x43) [reply src/has.ts:22]: It works; I even tested it in an HTTPS app in IE11. (I actually started out with a protocol relative URL, but Web Workers in FF don't like that.) The test URL doesn't have to be an active endpoint, just something the browser _could_ make a request to.

Comment (dasa) [reply src/has.ts:22]: 👍

Comment (szwoelf) [reply src/has.ts:22]: Great! Thanks.

**Review by dylans — APPROVED** [review]

**Review by rorticus — APPROVED** [review]
